# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-07 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('read_num', models.IntegerField()),
                ('content', models.TextField()),
                ('images', models.TextField()),
                ('blog_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.BlogType')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('upwd', models.CharField(max_length=30)),
                ('is_author', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='index.User'),
        ),
        migrations.AddField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(related_name='topics', to='index.User'),
        ),
        migrations.AddField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Topic'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
