# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-07 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogtype',
            table='blogtype',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='reply',
            table='reply',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
